region = "us-east-1"
ami = "sample-ami"
instance_type = "t2.micro"
instance_name = "MyfirstInstance-dev"

bucket_name = "myLtimTerraformBucket-dev"
dynamodb_table_name = "state-lock-dev"
billing_mode = "PROVISIONED"
hash_key = "UserId"
attribute_name = "LockID"
attribute_type = "S"
location_key = "myStateFile/terraform.tfstate"
