region = "us-east-1"
ami = "sample-ami"
instance_type = "t2.large"
instance_name = "MyfirstInstance-prod"

bucket_name = "myLtimTerraformBucket-prod"
dynamodb_table_name = "state-lock-prod"
billing_mode = "PROVISIONED"
hash_key = "UserId"
attribute_name = "LockID"
attribute_type = "S"
location_key = "myStateFile/prod/terraform.tfstate"
