---
name: GH-actions yaml
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Generate Tag
              id: tag
              uses: mazaheriMahdi/auto-tagger-action@v0.0.10
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Latest Tag
              run: echo "The Latest version ${{ steps.tag.outputs.tag }}"