name: Add tags

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true

      - name: Set up Git
        run: |
          git config --global user.name 'Arpita Patnaik'
          git config --global user.email 'arpita.10718326@ltimindtree.com'    

      - name: Fetch tags
        run: git fetch --tags

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Current version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: calculate the next version
        id: increment_version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          IFS='.' read -r -a VERSION_PARTS <<< "${VERSION#v}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      #Create and push the new tag
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.NEW_VERSION }}
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
